//! Manual REST route registration for `PaymentApi`.
//!
//! Most routes (`charge`, `get_invoice`) are generated by the
//! `#[toolkit::rest_contract]` macro — see
//! [`api_contracts_sdk::rest::register_payment_api_rest_routes`]. This file
//! keeps the **manual** `OperationBuilder` path for the two routes that opt
//! out of generation via `#[server_manual]`: the SSE `list_payments` stream and
//! the `multipart/mixed` `stream_payments` feed.
//!
//! It demonstrates that the macro-generated registration is *additive* — the
//! returned router is chained straight into hand-written `OperationBuilder`
//! calls. The manual path remains a first-class option for any route the
//! generator does not (yet) express (SSE, complex auth, custom shapes).

use std::sync::Arc;

use axum::{Extension, Router};
use toolkit::api::OpenApiRegistry;
use toolkit::api::operation_builder::OperationBuilder;

use api_contracts_sdk::contract::PaymentApi;
use api_contracts_sdk::contract_v2::PaymentApiV2;
use api_contracts_sdk::models::PaymentSummary;

use super::handlers;

const API_TAG: &str = "API Contracts \u{2014} Payments";

/// Register **all v1** `PaymentApi` REST routes — the full v1 set used by the
/// gear and the integration tests.
///
/// Composes the two v1 registration paths on one router:
/// 1. macro-generated routes (`charge`, `get_invoice`) via
///    [`api_contracts_sdk::rest::register_payment_api_rest_routes`];
/// 2. the two manual streaming routes via [`register_manual_routes`].
///
/// This is the canonical proof that generated and hand-written
/// `OperationBuilder` registration interoperate on the same router. For the
/// v2 routes see [`register_v2_routes`] — the two compose on one router.
#[allow(clippy::needless_pass_by_value)]
pub fn register_routes(
    router: Router,
    openapi: &dyn OpenApiRegistry,
    service: Arc<dyn PaymentApi>,
) -> Router {
    let router = api_contracts_sdk::rest::register_payment_api_rest_routes(
        router,
        openapi,
        Arc::clone(&service),
    );
    register_manual_routes(router, openapi, service)
}

/// Register the macro-generated **v2** routes under `/api-contracts/v2`.
///
/// Kept separate from [`register_routes`] so the two major versions compose on
/// one router independently (ADR-0007: parallel versions served side by side
/// during a migration window) — callers that only need v1 are unaffected.
/// v2 declares no `#[server_manual]` method, so it has no hand-written
/// counterpart and needs no `Extension` of its own.
pub fn register_v2_routes(
    router: Router,
    openapi: &dyn OpenApiRegistry,
    service_v2: Arc<dyn PaymentApiV2>,
) -> Router {
    api_contracts_sdk::rest_v2::register_payment_api_v2_rest_routes(router, openapi, service_v2)
}

/// Register the routes that are kept **manual** (not macro-generated).
///
/// The two streaming endpoints, both marked `#[server_manual]` on the
/// projection trait: `list_payments` over SSE and `stream_payments` over
/// `multipart/mixed`. `service` is layered as an axum [`Extension`] so both
/// streaming handlers can resolve `Arc<dyn PaymentApi>` per request.
///
/// Composes with the generated routes: call
/// `register_payment_api_rest_routes(router, openapi, svc)` first, then pass
/// the returned router here.
#[allow(clippy::needless_pass_by_value)]
pub fn register_manual_routes(
    router: Router,
    openapi: &dyn OpenApiRegistry,
    service: Arc<dyn PaymentApi>,
) -> Router {
    // GET /api-contracts/v1/payments — SSE stream of PaymentSummary items.
    let router = OperationBuilder::get("/api-contracts/v1/payments")
        .operation_id("api_contracts.list_payments")
        .summary("List payments (SSE)")
        .description(
            "Server-sent event stream of payment summaries, optionally filtered by \
             status and currency. The stream is terminated by a synthetic \
             `event: done` frame.",
        )
        .tag(API_TAG)
        .authenticated()
        .exposed()
        .no_license_required()
        // Even a hand-registered route should take its query parameters from
        // the struct's `#[derive(QueryParams)]` rather than restating them:
        // hand-written entries drift from the type the handler actually
        // decodes, and this route already extracts a `ListPaymentsFilter`.
        .query_params_from::<api_contracts_sdk::models::ListPaymentsFilter>()
        .handler(handlers::list_payments_handler)
        .sse_json::<PaymentSummary>(openapi, "SSE stream of PaymentSummary items")
        .standard_errors(openapi)
        .register(router, openapi);

    // GET /api-contracts/v1/payments/feed — the same items as the SSE route
    // over `multipart/mixed`, with a fallible open (#4734).
    //
    // `multipart_json` is `sse_json`'s counterpart: it declares a `200` whose
    // content type is `multipart/mixed` and whose declared schema is the *item*
    // type, since the framing is what turns one item into one part. The runtime
    // `boundary=` parameter is generated per response by
    // `MultipartJsonStream` and is deliberately not in the spec — the OpenAPI
    // media-type key is the bare `multipart/mixed`.
    let router = OperationBuilder::get("/api-contracts/v1/payments/feed")
        .operation_id("api_contracts.stream_payments")
        .summary("Payment feed (multipart/mixed)")
        .description(
            "Stream of payment summaries framed as `multipart/mixed`, one JSON part per \
             item. Unlike the SSE endpoint the open is a distinct operation: an \
             unacceptable filter is rejected with a normal problem response before any \
             part is written. The stream ends with the closing multipart delimiter; a \
             graceful end without it is a truncation and is surfaced as a transport \
             framing error.",
        )
        .tag(API_TAG)
        .authenticated()
        .no_license_required()
        .query_params_from::<api_contracts_sdk::models::ListPaymentsFilter>()
        .handler(handlers::payment_feed_handler)
        .multipart_json::<PaymentSummary>(openapi, "multipart/mixed stream of PaymentSummary items")
        .standard_errors(openapi)
        .register(router, openapi);

    // One `Extension` serves both streaming handlers: they are two methods of
    // the same contract, resolved under one `ClientHub` key.
    router.layer(Extension(service))
}
