//! Public API contract for the `AuthZ` resolver.
//!
//! `AuthZResolverClient` is a transport-agnostic `#[toolkit::contract]`: the
//! same trait is used for in-process consumption (the gear registers a local
//! impl in `ClientHub`) and for out-of-process consumption (a directory-
//! resolving REST client generated by the [`rest`](crate::rest) projection).
//! Consumers depend on it via `#[toolkit::consumes(contract = ..., from =
//! "authz-resolver")]` and never branch on the binding mode.

use toolkit_canonical_errors::CanonicalError;
use toolkit_security::SecurityContext;

use crate::models::{EvaluationRequest, EvaluationResponse};

/// Public API contract for the `AuthZ` resolver gateway (PDP).
///
/// Registered in `ClientHub` as `Arc<dyn AuthZResolverClient>` and consumed by
/// gears acting as Policy Enforcement Points (usually via
/// [`PolicyEnforcer`](crate::pep::PolicyEnforcer)).
///
/// Access denial is expressed via `EvaluationResponse.decision == false`, not
/// as an error; the `CanonicalError` return covers infrastructure/transport
/// failures only.
#[toolkit::contract(gear = "authz-resolver", version = "v1")]
pub trait AuthZResolverApi: Send + Sync {
    /// Evaluate an authorization request. Safe read (no side effects).
    ///
    /// `ctx` carries the caller's `SecurityContext`; over REST the generated
    /// client attaches its bearer token so the PDP can authenticate the call.
    ///
    /// # Errors
    ///
    /// Returns a `CanonicalError` on transport/infrastructure failure or when
    /// no `AuthZ` plugin is available. An allow/deny *decision* is returned as
    /// `Ok(EvaluationResponse)`.
    #[idempotency(SafeRead)]
    async fn evaluate(
        &self,
        ctx: SecurityContext,
        req: EvaluationRequest,
    ) -> Result<EvaluationResponse, CanonicalError>;
}
